#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2013
# 
#############################################################################

# Specify the location of the bmptk library
BMPTK      := ../../..

# Specify target chip or board or system
TARGET     := db104

# The Makefile.inc does all the work
include $(BMPTK)/Makefile.inc
