#############################################################################
# 
# Makefile that just passes the work to its subdirectories.
#
# (c) Wouter van Ooijen (www.voti.nl) 2015
#
# This file is in the public domain.
# 
#############################################################################

# code for the V1TH04 course at Hogeschool Utrecht (C)
SUBDIRS += v1th04

# code for the V2CPSE2 course at Hogeschool Utrecht (Assembler & C++)
SUBDIRS += v2cpse2

# The Makefile.subdirs does the work
include ../../Makefile.subdirs

