#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2013
# 
############################################################################# 

# Specify target chip or board or system
TARGET     := lpc1114fn28

# Specify the location of the bmptk library
BMPTK      := ../../..

# Specify project files (other than $(PROJECT).cpp) (if any)
SOURCES    := lcd5510.c timer.c
HEADERS    := lcd5510.h timer.h

# The Makefile.inc does all the work
include $(BMPTK)/Makefile.inc
