#############################################################################
# 
# Makefile that just passes the work to its subdirectories.
#
# (c) Wouter van Ooijen (www.voti.nl) 2015
#
# This file is in the public domain.
# 
#############################################################################

# all current 'chip' examples are for specific boards
# SUBDIRS += 

# The Makefile.subdirs does the work
include ../../Makefile.subdirs

