#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2013
# 
#############################################################################

# Specify the location of the bmptk library
BMPTK      := ../../..

# Specify target chip or board or system
TARGET     := db103

# Specify the project name, the default is main (.cpp, .c, or .asm)
# this is also the main .cpp file to compile
PROJECT    := 

# Specify project files (other than $(PROJECT).cpp) (if any)
OBJECTS    := 
SOURCES    := 
HEADERS    := 
LIBS       := 

# specify (extra) results you want to get (if any)
RESULTS    := 

# The Makefile.inc does all the work
include $(BMPTK)/Makefile.inc
