#############################################################################
# 
# Makefile that just passes the work to its subdirectories.
#
# (c) Wouter van Ooijen (www.voti.nl) 2012 ... 2015
#
# This file is in the public domain.
# 
#############################################################################

# examples for specific boards
SUBDIRS += boards

# eaxamples for bare chips
SUBDIRS += chips

# examples and other code for courses I give at the Hogeschool Utrecht
SUBDIRS += courses

# The Makefile.subdirs does the work
include ../Makefile.subdirs

